<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /home/leonardo/web/proyectofinal/vendor/bin/demosexto/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'demosexto' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=bdpropelsexto',
        'user' => 'leonardo',
        'password' => '1234',
      ),
    ),
    'default' => 'demosexto',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-demosexto-conf.php');
return $conf;